
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: zjm-analytics_dev
  username: db_dev
  password: password

test:
  <<: *default
  database: zjm-analytics_test
  username: db_dev
  password: password

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
